In [10]:
import torch

x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

print(x*y)

tensor([10.,  3.])


In [11]:
x = torch.zeros([2, 5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [12]:
x.shape

torch.Size([2, 5])

In [13]:
y = torch.rand([2, 5])
y

tensor([[0.1382, 0.4425, 0.9774, 0.9025, 0.6624],
        [0.1204, 0.8390, 0.3246, 0.4173, 0.8244]])

In [14]:
# This is a reshape
y.view([1, 10])

tensor([[0.1382, 0.4425, 0.9774, 0.9025, 0.6624, 0.1204, 0.8390, 0.3246, 0.4173,
         0.8244]])

In [15]:
y

tensor([[0.1382, 0.4425, 0.9774, 0.9025, 0.6624],
        [0.1204, 0.8390, 0.3246, 0.4173, 0.8244]])

In [18]:
y = y.view([1, 10])
y

tensor([[0.1382, 0.4425, 0.9774, 0.9025, 0.6624, 0.1204, 0.8390, 0.3246, 0.4173,
         0.8244]])